### ISSUE TITLE
row cell not taking the entire height

### ISSUE THREAD

**Issue by SunlessCrane** [SunlessCrane/Netflix-Geyu#1]
In the home view, I created some dummy cells to be the placeholder for images. Yet, each green cell is not taking the entire cell height.

![simulator_screenshot_90F1C83E-BF4B-46C7-98F8-88894EDB0CD2](https://user-images.githubusercontent.com/66064357/189539754-267e218f-e0ab-4113-98eb-0cfab693279f.png)

**Comment by SunlessCrane** [comment]
[Commit here ](https://github.com/SunlessCrane/Netflix-Geyu/commit/f75bc2566ea08ee3ffc93f42c647fa97c1cba61d)

**Comment by Spark-RTG** [comment]
You can try to define the cell size in collectionView.
```layout.itemSize = CGSize(width: 140, height: 200)```
